### ISSUE TITLE
Better onerror Error message

### ISSUE THREAD

**Issue by alexbiehl** [slamdata/purescript-affjax#10]
Hey, upon experimenting with your library, I found the Error thrown in case of some XHR failure not very useful, 

`Exception.message err` results in `"undefined"` and `show err` ends up with `[object XMLHttpRequestProgressEvent]`. Maybe it is possible to get a more meaningful message from the `onerror` handler.

**Comment by garyb** [comment]
Thanks, I'll look into it. Do you know what situation raised the error?

**Comment by alexbiehl** [comment]
I hadn't prefixed the url with "http://". I debugged the js and it seems there isn't an error message provided. A look into https://github.com/jquery/jquery/blob/76df9e4e389d80bff410a9e5f08b848de1d21a2f/src/ajax/xhr.js#L117
suggests that event jQuery doesn't do more than pass `'error'` to the callback..

**Comment by garyb** [comment]
Ok, well thanks for the example anyway. I'm sure we can do better than `"undefined"` or `[object XMLHttpRequestProgressEvent]` at least!

**Comment by alexbiehl** [comment]
Ah, a closer look reveals: 
https://github.com/jquery/jquery/blob/76df9e4e389d80bff410a9e5f08b848de1d21a2f/src/ajax/xhr.js#L92-L97
