### ISSUE TITLE
Remove Requestable/Respondable

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-affjax#102]

**Comment by damncabbage** [comment]
Agreed on this (for what it's worth). For people who don't see the problem with it:

Consider the case where you PUT to a service, and it either returns an HTTP 400 and a chunk of JSON telling you what you got wrong (for example), or a blank [HTTP 201 indicating success](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT).

Unfortunately, `Respondable Unit` doesn't let you see the error, and `Respondable Json` explodes on the blank response. So to handle the above scenario with `Respondable`, you need to pick the lowest common denominator between the two responses (`Respondable String`) and do the JSON parsing yourself anyway.

**Comment by garyb** [comment]
Resolved by #107
