### ISSUE TITLE
Bad Url

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [slamdata/purescript-affjax#128]
I have been trying to handle if there is a bad URL given to `AX.get`

```purescript
main = launchAff $ do
  res1 <- AX.get ResponseFormat.json "/badurl"
```

Reading through the [purescript-aff docs](https://pursuit.purescript.org/packages/purescript-aff/5.0.1) "Dealing with Failure", but I haven't seen an easy way to accomplish this.

**Comment by garyb** [comment]
You won't be able to catch that as a specific error, since it's one of the general `Error`s that XHR might raise, but if you `try` the affjax functions it will lift things from the `Aff` error channel into an `Either` instead.

**Comment by BebeSparkelSparkel** [comment]
Thanks for the tip.
Not trying to be stupid but the following

```purescript
main = do
  req <- try $ launchAff $ AX.get AXRes.string "http://localhost:5000"

  log case req of
      Left _ -> "left"
      Right _ -> "right"
```

Gets the following error:
```text
* Build successful.
* Main.main is not suitable as an entry point because it:
*
*  - has a Control.Monad.Error.Class.MonadError constraint
*
* If you need to create a JavaScript bundle without an entry point, use
* the --skip-entry-point flag.
*
* If you are certain that Main.main has the correct runtime
* representation, use the --check-main-type or --no-check-main flags
* to amend or skip this check.
*
* ERROR: Failed entry point check for module Main
```

**Comment by garyb** [comment]
The `launchAff` still should go on the outside, you want to `try` the individual actions within it:

``` purescript
main = launchAff $ do
  res1 <- try $ AX.get ResponseFormat.json "/badurl"
  ...
```

`launchAff` turns a block of `Aff` into an `Effect`, so you generally only have one of those at the very top level of the program.

**Comment by Benjmhart** [comment]
@garyb  Doesn't this technically make `AX.get` a partial function?   these errors should be exposed by default at the type level.

**Comment by BebeSparkelSparkel** [comment]
It does expose the error but is not specific about the reason for failure.
https://pursuit.purescript.org/packages/purescript-simple-ajax/0.5.0/docs/Simple.Ajax#v:get

**Comment by safareli** [comment]
you might wanna look at https://github.com/slamdata/purescript-aff#dealing-with-failure

**Comment by garyb** [comment]
:point_up: what he said, but yeah, I think in a future version perhaps all error should arrive on the `Left` as it's just one less thing to think about then. 🙂

**Comment by Benjmhart** [comment]
@garyb  - Since the type system does not complain about a potential Error, I would really encourage that,  I'm glad I found the error and got instructions on how to handle it,  but any potential for a runtime error should be exposed at the type level.

**Comment by garyb** [comment]
Well, it kinda does - `Aff` implies exceptions via `Error`. Maybe we'll get around to having bifunctor `Aff` to make the error channel even more explicit at some point, but currently you have to assume any `Aff` needs to be `try`ed if you want to catch errors.

**Comment by Benjmhart** [comment]
i suppose i consider this a feature request - if approved I would be happy to work on it. 

if API change is a concern,  perhaps a safeGet/safePost etc function should be included.

**Comment by garyb** [comment]
The Aff error channel is no longer used in the latest release, potential XHR errors are captured and the request functions return `Either` with an error type that covers the various possibilities.

**Comment by Benjmhart** [comment]
@garyb this is snazzy!

**Comment by BebeSparkelSparkel** [comment]
Nice
