### ISSUE TITLE
Handle ill-formed `FormURLEncoded` data

### ISSUE THREAD

**Issue by menelaos** [slamdata/purescript-affjax#139]
A fairly recent [commit](https://github.com/purescript-contrib/purescript-form-urlencoded/commit/8b0b6e7a4af1267882eddaa0412063ce0a41c17e) in `purescript-form-urlencoded` changed the type signature of the `encode` function from `... -> String` to `... -> Maybe String`. This trips up the [`extractContent`](https://github.com/slamdata/purescript-affjax/blob/ec9c50e35980ba33b4bc7a3bc026970ba27bf767/src/Affjax.purs#L274) function in `purescript-affjax`.  Due to the use of `unsafeToForeign`, the compiler won't notice. 

The sanitization of the `FormURLEncoded` data could probably also be done in `purescript-form-urlencoded` (smart constructors or similar) but, either way, I guess the user should be prevented from sending ill-formed requests. 
Thanks for reading!

**Comment by garyb** [comment]
Yikes, well spotted. Untyped `unsafeCoerce` strikes again!

**Comment by garyb** [comment]
Ah, this does only arise if the dependency versions are overridden right now, at least.

**Comment by menelaos** [comment]
Yes, sorry, I should have mentioned that I was using `affjax` v9.0.0 and `form-urlencoded` v5.0.0. They were in the same package set, but I see that you [took care](https://github.com/purescript/package-sets/issues/467) of that, too :-) Thanks!

**Comment by garyb** [comment]
I'll get an update out this weekend, just ran out of time last night 🙂
