### ISSUE TITLE
not in package set?

### ISSUE THREAD

**Issue by swuecho** [slamdata/purescript-affjax#144]
spago: The following packages do not exist in your package set:
  - affjax

https://github.com/purescript/package-sets/releases/download/psc-0.13.4/packages.dhall sha256:205829948db98d5bab8cd74e811de9b0d2a6bf3802031904db4007ee6d773a28

**Comment by garyb** [comment]
Yeah, it needs some work before it's compatible: #141

**Comment by swuecho** [comment]
I see. thanks for the excellent work.

**Comment by garyb** [comment]
There's a PR up to restore it to the package set at last: https://github.com/purescript/package-sets/pull/534 🙂
