### ISSUE TITLE
Can't get it working with psc 0.7.4.1

### ISSUE THREAD

**Issue by dbushenko** [slamdata/purescript-affjax#45]
My bower.json is:

{
  "name": "purstest",
  "version": "1.0.0",
  "moduleType": [
    "node"
  ],
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "output"
  ],
  "dependencies": {
    "purescript-console": "^0.1.0",
    "purescript-jquery": "^0.5.0",
    "purescript-smolder": "^3.0.1",
    "purescript-affjax": "^0.5.0"
  }
}

I can't build the project with purescript-affjax:

dim@Aldan-3L ~/W/purstest> pulp build
* Building project in /home/dim/Work/purstest
psc: No files found using pattern: src/**/*.js
Error found:
Error at /home/dim/Work/purstest/bower_components/purescript-affjax/src/Network/HTTP/Affjax/Request.purs line 7, column 13 - line 7, column 23:
  Module DOM does not export type Document
See https://github.com/purescript/purescript/wiki/Error-Code-UnknownImportType for more information, or to contribute content related to this error.

* ERROR: Subcommand terminated with error code 1

**Comment by garyb** [comment]
Looks like you have old dependencies installed if it's failing to resolve that - you'll need `purescript-dom@^0.2.0`.

**Comment by garyb** [comment]
Ah sorry, in fact you have an old version of `affjax` too, you'll need 0.7.0 for it to work with psc 0.7.3 or newer.

**Comment by dbushenko** [comment]
bower purescript-affax#^0.7.0          ENOTFOUND Package purescript-affax not found
:-(

**Comment by garyb** [comment]
You misspelled "affjax" :smile:

**Comment by dbushenko** [comment]
Oh, you are fast! :-)

**Comment by dbushenko** [comment]
Thanks for help! Got it compiling! :-)

**Comment by garyb** [comment]
Glad to hear it!
