### ISSUE TITLE
Add ArrayBufferResponse response handling

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-affjax#5]

**Comment by garyb** [comment]
I'm a bit stumped with this one, mainly because I've not figured what an `ArrayBuffer` response from the server is supposed to look like. 

I tried to make an `express` endpoint do it, trying everything I could think of, and it came across as JSON or a `Blob` - both of which are then interpreted incorrectly when the `responseType` is set to `ArrayBuffer` (they are coerced into `ArrayBuffer`s, but have entirely the wrong value).

I've not had much luck finding specs or documentation for the format of these responses either.

Should I just drop `ArrayBuffer` response support for now, until we have a test case?

/cc @jdegoes

**Comment by jdegoes** [comment]
Let's ignore it until we have a use case.
