### ISSUE TITLE
Use purescript-media-types

### ISSUE THREAD

**Issue by zudov** [slamdata/purescript-affjax#61]
@garyb made [purescript-media-types](https://pursuit.purescript.org/packages/purescript-media-types/0.1.1) yesterday. I guess the plan is that `purescript-affjax` would use it at some point. If it's :+1: I can make a PR.

**Comment by garyb** [comment]
I'd like to break out the methods, headers, and status codes too, so perhaps we should do them all at once.

I'm not sure what the breakdown of these things should be though, maybe all 3 of those just need to go into a new library rather than being split any further?

**Comment by jonsterling** [comment]
Should we also try and use this library for halogen? (media types are used in the html stuff)

**Comment by zudov** [comment]
Doing them all at once would be of course better.

I guess it won't hurt to have extra granularity, but at the moment I can't come up with a good use case where you would need only one of those modules.

**Comment by garyb** [comment]
@jonsterling :+1: 

@zudov I'll sort something out tonight.

**Comment by zudov** [comment]
I believe this was addressed in https://github.com/slamdata/purescript-affjax/commit/86e85687f8184bcb07c201e21569793e825a9978
