### ISSUE TITLE
Cookie support?

### ISSUE THREAD

**Issue by tdammers** [slamdata/purescript-affjax#95]
I'm trying to get an Affjax-based application to authenticate against an API using cookies; however, the usual way of relying on AJAX calls to transparently carry cookies over doesn't seem to work. The POST to `/login` correctly sets a new session cookie, but subsequent requests do not send it along.

Is there some sort of flag I need to set in order to make this work?

EDIT: it may be of interest that I'm doing cross-site AJAX here, so I probably need a way to set the `withCredentials` option on the xhr request?

**Comment by tdammers** [comment]
Nevermind, found it.

**Comment by abritov** [comment]
is it work in nodejs?
